# Generated by Django 3.0.1 on 2020-01-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191223_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(max_length=200)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
